### ISSUE TITLE
Print ready JSON Generated

### ISSUE THREAD

**Issue by Business360** [NielsLeenheer/ReceiptPrinterEncoder#10]
Hi

The generated JSON is only the JSON code that's ready to be printed right?

We still need to write our own code to connect and send this code to the printer?

**Comment by NielsLeenheer** [comment]
The output of the library isn"t JSON, but yes the data it generates is ready to be send to the printer. 

The code to achieve that needs to be written. That is not part of the library. I did create several libraries for sending data to the printer from the browser using WebSerial, WebBluetooth or WebUSB. But there are many ways to do that.
