### ISSUE TITLE
V3 is not registered

### ISSUE THREAD

**Issue by palagonKevo** [NielsLeenheer/ReceiptPrinterEncoder#19]
I've tried to install @point-of-sale/receipt-printer-encoder but it's not registered.

![image](https://github.com/user-attachments/assets/e7a11686-72ba-44e1-9c71-dca8c2537f5a)

I have tried both yarn and npm and neither of them is working.

**Comment by NielsLeenheer** [comment]
This is correct. It will be published later today, or tomorrow, depending on the time I have to wrap up the last details.

**Comment by NielsLeenheer** [comment]
Version 3 is now up.
