### ISSUE TITLE
Uncaught Error: Codepage not supported by printer

### ISSUE THREAD

**Issue by jswangtao** [NielsLeenheer/ReceiptPrinterEncoder#3]
Follow the example code Codepage in readme.md
```
let result = encoder
    .codepage('windows1251')
    .text('Iñtërnâtiônàlizætiøn')
    .codepage('cp936')
    .text('简体中文')
    .encode()
```
 Uncaught Error: Codepage not supported by printer

**Comment by jswangtao** [comment]
I want to print Simplified Chinese, but it seems that CP936 does not support it

**Comment by NielsLeenheer** [comment]
CP936 is generally not supported by printers, so it has been removed from the documentation.
