### ISSUE TITLE
Printer is feeding paper when only pulse command is sent

### ISSUE THREAD

**Issue by cervantes-x** [NielsLeenheer/ReceiptPrinterEncoder#34]
Since version 3, when sending only a pulse command to the printer, it feeds a little bit of paper.

### Code example:
```
    const result = new ReceiptPrinterEncoder({
      columns: printer.width,
    });

    result.initialize().pulse();

    const encoded = result.encode();
```

### Expected Behavior:
Don't feed paper when nothing has been printed.

### Actual Behavior:
Printer is feeding a little bit of paper.

**Comment by NielsLeenheer** [comment]
Should be fixed in the upcoming release

**Comment by cervantes-x** [comment]
I've installed version 3.0.2 with the implemented fix. My printers are still feeding a bit of paper after only sending the pulse command.

**Comment by cervantes-x** [comment]
I found out that it only happens when the initialize command is included. When I just use ```encoder.pulse().encode()```. It doesn't feed the paper anymore.
