### ISSUE TITLE
Encoder feed

### ISSUE THREAD

**Issue by palagonKevo** [NielsLeenheer/ReceiptPrinterEncoder#37]
I've been using the previous version of this project, and after I update to this one I've been using some ESC/POS commands in order to open the cashier box, and so on.

For this purpose I send just a pulse and should work as long as the printer is connected to the cashier box, the problem is that after the update, every time I send `encoder.pulse().encode()` the printer keeps outputting some feed like there was something in the config that makes it do that.

What should I do in this case?

**Comment by NielsLeenheer** [comment]
This is fixed in the next release (See #34)
