### ISSUE TITLE
 .align('center') not working after upgrade to v3.0.0

### ISSUE THREAD

**Issue by lajith111** [NielsLeenheer/ReceiptPrinterEncoder#39]
` .align('center').height(size).line(print.RecieptName ?? '',32).height(1)`

Here print.RecieptName not constanct value.. after i search  align is deprecated..

How can i achived same using new version..Please let me know

**Comment by NielsLeenheer** [comment]
Align should still work. Not aware of any issues. But the second argument of the `line()` function is no longer supported. To archive a similar effect you can use the `box()` function with a style of `none`.

```
encoder
    .align('center')
    .box(
        { width: 32, align: 'center', style: 'none'}, 
        'The quick brown fox jumps over the lazy dog. ' + 
        'The quick brown fox jumps over the lazy dog. ' + 
        'The quick brown fox jumps over the lazy dog'
    )
```

Try pasting this in the playground to see the effect: https://point-of-sale.dev/receipt-printer/playground

<img width="441" alt="Screenshot 2024-10-25 at 21 27 06" src="https://github.com/user-attachments/assets/e0d7764d-f419-4090-977f-a2aff4064d0d">

**Comment by lajith111** [comment]
Ok..Thank You..
