### ISSUE TITLE
Table column alignment is not working

### ISSUE THREAD

**Issue by SridharKanilebettu** [NielsLeenheer/ReceiptPrinterEncoder#40]
A 58mm thermal printer (MPT II) is being tested which included lines of Texts and tables via USB. Printing is working but the table column alignment is not working as expected for right alignment. Below is the code snippet used.
`encoder.table(
    [
        { width: 15, align: 'left', marginRight: 1 },
        { width: 9, align: 'right', marginRight: 1 },
        { width: 16, align: 'right' }
    ],    
    [
        [
            (encoder) => encoder.bold(true).text('Name').bold(false),
            (encoder) => encoder.bold(true).text('Quantity').bold(false),
            (encoder) => encoder.bold(true).text('Description').bold(false)
        ],
        [
            (encoder) => encoder.rule({ width: 6 }),
            (encoder) => encoder.rule(),
            (encoder) => encoder.rule({ style: 'double' }),
        ],
        ['Banana', '5', 'Ripe Yellow Bananas'],
        ['Cherry', '250000000', 'Delicious Sweet Cherries'],
        [
            (encoder) => encoder.text('Cherry'),
            (encoder) => encoder.width(2).text('250000000').width(1),
            (encoder) => encoder.text('Delicious Sweet Cherries')
        ],
        [
            (encoder) => encoder.bold(true).text('Cherry').bold(false),
            (encoder) => encoder.text('250000000'),
            (encoder) => encoder.bold(true).text('Delicious Sweet Cherries').bold(false)
        ],
        ['[-------------]', '[-------]', '[--------------]']
    ]
)`

Output:
![github](https://github.com/user-attachments/assets/639fab0e-65f5-4729-b2cd-23839c6f80e5)

**Comment by lajith111** [comment]
@SridharKanilebettu which plugin you r using to connect & write?

**Comment by SridharKanilebettu** [comment]
"esc-pos-encoder": "^3.0.0"

**Comment by SridharKanilebettu** [comment]
This is an angular project. Installed using npm, and the encoder initialization code is written below. Can't figure out why the encoder fails to execute 'align' inside table.

`import { Injectable } from '@angular/core';
import EscPosEncoder from 'esc-pos-encoder';

@Injectable({
  providedIn: 'root'
})
export class WebUSBPrintService {
  private device: any | null = null;
  private devices: any | null = null;
  encoder = new EscPosEncoder();

  constructor() {}

  // Request a USB device (filtered by vendorId or other criteria)
  async requestDevice(productFamily:string): Promise<void> {
    try {
        console.log('Device selection started:');
        this.devices = await (navigator as any).usb.getDevices();
        console.log('Already paired devices:', this.devices);
        if(this.devices == null || this.devices.length == 0){
            console.log('Device needs pairing:====>', this.devices);
            this.device = await (navigator as any).usb.requestDevice({
                    filters: [{ productName: productFamily }] // Replace with your printer's vendorId
            });
        }else{
          console.log('Device selected from already paired:', this.devices,productFamily);
          this.device = this.devices.filter((device) => device.productName == productFamily)[0];
          if(this.device == null ){
            this.device = await (navigator as any).usb.requestDevice({
              filters: [{ productName: productFamily }] // Replace with your printer's vendorId
            });
          }  
          
        }
        console.log('Device selected:', this.device);
    } catch (error) {
      console.error('Error requesting USB device:', error);
      throw error;
    }
  }

  // Open and claim the USB interface
  async openDevice(): Promise<void> {
    if (!this.device) {
      throw new Error('No device selected.');
    }
    try {
      await this.device.open();
      if (this.device.configuration === null) {
        await this.device.selectConfiguration(1); // Select default configuration
      }
      console.log('device opened');
      await this.device.claimInterface(0); // Claim the printer's interface
      console.log('Device opened and interface claimed.');
    } catch (error) {
      console.error('Error opening the device:', error);
      throw error;
    }
  }

  // Send data to the printer (e.g., Hello World)
  async sendPrintData(encodedPOSText: any): Promise<void> {
    if (!this.device) {
      throw new Error('No device selected.');
    }
    try {
      // Send data to endpoint 1 (replace with correct endpoint for your device)
      console.log('Device endpoints',this.device.configuration.interfaces[0]?.alternate);
      await this.device.transferOut(this.device.configuration.interfaces[0]?.alternate.endpoints.find((obj: any) => obj.direction === 'out').endpointNumber, encodedPOSText);
      //console.log('Data sent to the device:', message);
    } catch (error) {
      console.error('Error sending data:', error);
      throw error;
    }
  }

  // Close the device after use
  async closeDevice(): Promise<void> {
    if (this.device) {
      await this.device.close();
      //await this.device.forget();
      this.device = null;
      console.log('Device closed.');
    }
  }
}
`

**Comment by SridharKanilebettu** [comment]
It worked after changing the library. Thanks!
